branch-defaults:
  Master:
    environment: udagram-kike-dev
  default:
    environment: null
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-kike
  branch: null
  default_ec2_keyname: AWS_KIKE
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
